name: Build Flutter Web and Deploy to docs/

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Copy to docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit and push
        run: |
          git config neveraskaab github-actions
          git config ahmetabesli@gmail.com github-actions@github.com
          git add docs
          git commit -m "Automated build to docs folder" || echo "No changes to commit"
          git push
